### ISSUE TITLE
App wake up

### ISSUE THREAD

**Issue by ir4y** [beda-software/telemedicine-demo-mobile#4]
There are some issues with app wake up.
It works just fine at the first release, however, now it is broken.

App should show call screen for all this stages
- [x] ios open
- [x] ios background
- [x] ios removed
- [x] ios blocked (unlock screen)
- [x] ios blocked (display is on)
- [x] android open
- [x] android background
- [x] android removed
- [x] android blocked (display is on)
- [x] android blocked (display is off)
On Android:
The app is open and then I block a screen, turn the display off.
Call to the app. The display is still off. After I manually turn the display on, the call screen appears.

If it is a cert issue let's resolve it and don't change cert setup on the voximplant side to keep TestFlight version always working.

**Comment by ruscoder** [comment]
I've checked this IOS again - and everything is OK. I don't know what changed, but in the previous time we deployed the app - I just re-binded certs from our app to another and from another to ours.

**Comment by ruscoder** [comment]
Also, I've checked the android app in the emulator - everything is OK in all the cases. 
@ir4y Give more details about the Android version and your device. I'll try to repeat these settings in the emulator.

**Comment by ir4y** [comment]
It was voximplant bug with cers
